[package]
name = "lightify"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
crossterm = "0.29.0"
dirs = "7.0.0"
librespot = "0.8.0"
librespot-oauth = "0.8.0"
ratatui = "0.30.2"
reqwest = { version = "0.13.5", features = ["json"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = "1.53.1"

[build-dependencies]
vergen = "=9.0.6"
